# Stage 1: Build binary
FROM golang:1.24-bullseye AS builder

RUN apt-get  update && apt-get install -y git build-essential

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main_app ./cmd/app/main.go

# Stage 2: Final runtime
FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    chromium \
    wget curl unzip \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgbm1 \
    libglib2.0-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/main_app ./main_app

ENV PATH="/usr/lib/chromium/:${PATH}"
ENV ROD_HEADLESS=true

EXPOSE 8080

CMD ["./main_app"]