// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/logger/{logID}": {
            "get": {
                "description": "Get Request Result By LogID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Log"
                ],
                "summary": "Get Request Result",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/manager.LogMock"
                        }
                    }
                }
            }
        },
        "/api/v1/scrapper/request": {
            "post": {
                "description": "Request Scrapper to begin the process",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "Request Scrapper",
                "parameters": [
                    {
                        "description": "Fields",
                        "name": "fields",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manager.PageScrapRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/manager.PerPageResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "enum.LogStatus": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "Unknown",
                "Queued",
                "Pending",
                "Succeed",
                "Failed"
            ]
        },
        "manager.LogMock": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "console": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hasInfo": {
                    "type": "boolean"
                },
                "processedEpisodes": {
                    "type": "integer"
                },
                "processedFiles": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/enum.LogStatus"
                },
                "timeEstimated": {
                    "type": "integer"
                },
                "totalEpisodes": {
                    "type": "integer"
                },
                "totalFiles": {
                    "type": "integer"
                },
                "webhookSend": {
                    "type": "boolean"
                }
            }
        },
        "manager.PageScrapRequest": {
            "type": "object",
            "properties": {
                "authorization": {
                    "type": "string"
                },
                "pages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "webhookUrl": {
                    "type": "string"
                }
            }
        },
        "manager.PerPageResponse": {
            "type": "object",
            "properties": {
                "logId": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer [...]",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Comic Scrapper",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
