name: Build, Release & Push Docker Images

on:
  push:
    tags:
      - "v*" # فقط وقتی روی تگ push شد اجرا میشه

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: comic_scrapper
            context: .
            dockerfile: cmd/app/Dockerfile
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.context }}/${{ matrix.service.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ github.ref_name }}

  fire-on-server:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Trigger deployment on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/comic_scrapper
            git pull origin main
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f
            docker image prune -f
